#!/bin/bash
# Init
echo -e "\
#######################################################\n\
# 1. Focus on what is the most significant\n\
# 2. Done first, perfect second.\n\
# 3. Life is short, so script first.\n\
# 4. Try the easier version if stucked.\n\
# 5. Build your tools after you had done your jobs.\n\
######################################################"

# Import
for u in ${HOME}/.utils/*; do
	source ${u}
done

# Export 
## Basic
dprompt()
{
	local retcode=$(printf '%03d' $?)
	local kaomoji="(= _ =)"
	if [[ -n $(jobs) ]]; then
		kaomoji="(> 3 <)"
	fi
	if [[ ${retcode} -ne 0 ]]; then
		kaomoji="\e[31m(> x <)\e[0m"
	fi
		
	PS1="\e[0m(\j ${retcode} \u@\h \w)\e[0m\n${kaomoji} >>> "
}
export POWERLINE=$HOME/.vim/bundle/powerline
export PYTHONPATH=$PYTHONPATH:${POWERLINE}
export PS2="(! O_O) ... "
#export LC_ALL=zh_CN.UTF8
export EDITOR=vim
export PATH=$HOME/.local/bin:$PATH:${POWERLINE}/scripts
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
## C/C++
export LIBRARY_PATH=$HOME/.local/lib:$LIBRARY_PATH
export LD_LIBRARY_PATH=$HOME/.local/lib:$LD_LIBRARY_PATH
export LD_RUN_PATH=$HOME/.local/lib:$LD_RUN_PATH
export C_INCLUDE_PATH=$HOME/.local/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$HOME/.local/include:$C_INCLUDE_PATH
## Java
export JAVA_HOME=/Applications/Android\ Studio.app/Contents/jre/jdk/Contents/Home/
export JAVA_SDK=$JAVA_HOME/bin:${HOME}/Library/Android/sdk
export PATH=$PATH:$JAVA_HOME/bin:${JAVA_SDK}/tools/bin/:${JAVA_SDK}/platform-tools:${JAVA_SDK}/build-tools/28.0.3:${JAVA_SDK}/dex2jar-2.0
export CLASSPATH=.:$JAVA_HOME/lib/tools.jar:$JAVA_HOME/lib/dt.jar
## TeX
export TEXHOME=/usr/local/texlive/2013
export MANPATH=$MANPATH:$TEXHOME/texmf-dist/doc/man
export PATH=$PATH:$TEXHOME/bin/i386-linux
if [[ -f ${POWERLINE}/scripts/powerline-daemon ]]; then
  powerline-daemon -q
  source ${POWERLINE}/powerline/bindings/bash/powerline.sh
else
  export PROMPT_COMMAND='dprompt'
fi

# if [[ -n $(pidof xbindkeys) ]]; then
# 	killall xbindkeys
# fi
# xbindkeys

# Alias
alias ..="cd .."
alias ...="cd ../.."
alias ll="ls -lh"
alias la="ls -lah"
alias m=make
alias ue=". ~/.profile"
## Directory
alias cde="cd $HOME/env"
alias cdp="cd $HOME/project"
alias cdm="cd $HOME/Music"
alias cdo="cd $HOME/Downloads"
alias cdv="cd $HOME/Videos"
## Core Tools
alias cpr="cp -rf"
alias cprl="cp -rlf"
alias mkdp="mkdir -p"
alias rmr="rm -rf"
alias pst="pstree $USER"
alias psg="ps aux | grep -v grep | grep"
alias envg="env | grep"
alias ka="killall"
alias dush="du -sh"
## Application
alias mpgl="mpg123 -C -z *"
alias vi="vim"
### Git
DGIT=https://dwylkz@github.com/dwylkz
alias gitcl="git clone"
alias tgitcl="tsocks git clone"
alias gitpl="git pull -v"
alias tgitpl="tsocks git pull -v"
alias gitph="git push -v"
alias tgitph="tsocks git push -v"
alias gitcm="git commit"
alias gitco="git checkout"
alias gitbr="git branch"
alias gitaa="git add --all"
alias gitst="git status"
function gitci()
{
  local wording="up"
  if [[ -n ${1} ]]; then
    wording="${1}"
  fi
  git add --all
  git commit -m ${wording}
  git push -v
}

#. ~/.bashrc

##
# Your previous /Users/yangwudong/.profile file was backed up as /Users/yangwudong/.profile.macports-saved_2018-10-10_at_17:55:21
##

# MacPorts Installer addition on 2018-10-10_at_17:55:21: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.


# MacPorts Installer addition on 2018-10-10_at_17:55:21: adding an appropriate MANPATH variable for use with MacPorts.
export MANPATH="/opt/local/share/man:$MANPATH"
# Finished adapting your MANPATH environment variable for use with MacPorts.

export ALL_PROXY=***REMOVED***
