"Setting
colorscheme desert
syntax on
filetype on
filetype plugin indent on

set autochdir
set foldmethod=syntax
set incsearch
set nocompatible
set noswapfile
set number
set ruler
set shiftwidth=2
set tabstop=2
set autoindent
set smartindent
set expandtab
set hlsearch

""Browser
let g:netrw_liststyle=3
let mapleader=","
""Html
let g:html_indent_script1="inc"
let g:html_indent_style1="inc"

"Function
func! ErrorList()
	exec "clist"
endfunc
func! Make(target)
	exec "wa"
	exec "make!" a:target
endfunc
func! Browser()
	exec "15vs ."
endfunc

"Map
""Basic
imap jj <ESC>
map <C-a> ggVG
vmap <C-y> "+y
map <C-p> "+p
map <F2> <ESC>:call Browser()<CR>
map <F3> <ESC>:tabe  
map <F4> <ESC>:tabp<CR>
map <F5> <ESC>:tabn<CR>
map <F7> <ESC>:call ErrorList()<CR>
""Make
map <F8> <ESC>:call Make("debug")<CR>
map <F9> <ESC>:call Make("")<CR>
map <F10> <ESC>:call Make("run")<CR>

"Abbreviate
autocmd BufReadPre,BufRead,BufNew *.qml :set filetype=qml
