set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
"Plugin 'Valloric/YouCompleteMe'
Plugin 'Fuck/plantuml.vim'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
call vundle#end()
filetype plugin indent on

colorscheme desert
syntax on
filetype on
filetype plugin indent on

set encoding=utf-8
set autochdir
set foldmethod=syntax
set incsearch
set nocompatible
set noswapfile
set number
set ruler
set shiftwidth=2
set tabstop=2
set autoindent
set smartindent
set expandtab
set hlsearch
set t_Co=256

""Browser
let g:netrw_liststyle=3
""Html
let g:html_indent_script1="inc"
let g:html_indent_style1="inc"
let g:airline_theme="jellybeans"
let g:airline#extensions#tabline#enabled=1
"let g:airline_powerline_fonts = 1
let g:airline_highlighting_cache = 1
"let g:airline#extensions#tabline#left_sep = '>'
"let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#formatter = 'default'
"let g:airline_left_sep=''
"let g:airline_left_alt_sep='>'
"let g:airline_right_sep='<'
"let g:airline_detect_modified=1

"Function
func! ErrorList()
	exec "clist"
endfunc
func! Make(target)
	exec "wa"
	exec "make!" a:target
endfunc
func! Browser()
	exec "15vs ."
endfunc

"Map
""Basic
let mapleader="\\"
imap jj <ESC>
map <C-a> ggVG
vmap <C-y> "+y
map <C-p> "+p
map <leader>2 <ESC>:call Browser()<CR>
map <leader>3 <ESC>:tabe  
map <leader>4 <ESC>:tabp<CR>
map <leader>5 <ESC>:tabn<CR>
map <leader>7 <ESC>:call ErrorList()<CR>
""Make
map <leader>8 <ESC>:call Make("debug")<CR>
map <leader>9 <ESC>:call Make("")<CR>
map <leader>10 <ESC>:call Make("run")<CR>

"Abbreviate
autocmd BufReadPre,BufRead,BufNew *.qml :set filetype=qml
