#!/bin/bash
# directory util

CDLDB=${HOME}/.cdldb
if [[ ! -f ${CDLDB} ]]; then
	touch ${CDLDB}
fi

,() {
	local DIST=..
	for ((i = 0; i < ${#1}; i++)); do
		DIST+="/.."
	done
	cd ${DIST}
}

alias ,,="cd -"
alias ,a="pwd | todo ${CDLDB} a"
alias ,d="todo ${CDLDB} d"
_,g()
{
	if [[ ${COMP_CWORD} == 1 ]]; then
		local opts=$(todo ${CDLDB} s | sed 's,\t,->,g')
		COMPREPLY=(${opts})
	fi
}
complete -F _,g ,g
,g()
{
	cd $(todo ${CDLDB} n ${1})
}
