#!/bin/bash

package=$(cat<<__EOF__
	autoconf
	automake
	cantarell-fonts
	fakeroot
	gconf
	gdb
	ghc
	harfbuzz-icu
	ibus
	ibus-libpinyin
	ibus-pinyin
	icu
	libtools
	make
	mplayer
	mupdf
	nvidia
	opus
	pcmanfm
	python2-gobject
	python2-pyopenssl
	valgrind
	wget
	wqy-zenhei
	xmobar
	xmonad
	xmonad
	xmonad-contrib
	xorg-apps
	zip
__EOF__)

sudo pacman -Sy ${package}

aur=$(cat<<__EOF__
	http://lug.mtu.edu/archlinux/community/os/i686/xmonad-contrib-0.11.3-1-i686.pkg.tar.xz
	https://aur.archlinux.org/packages/hs/hsetroot/hsetroot.tar.gz
	https://aur.archlinux.org/packages/go/google-chrome/google-chrome.tar.gz
	https://aur.archlinux.org/packages/tt/ttf-google-fonts-git/ttf-google-fonts-git.tar.gz
__EOF__)

for i in ${aur}; do
	wget ${i}
done

for i in *.tar.gz; do
	tar xvf ${i}
done

for i in *; do
	if [[ ! -d ${i} ]]; then
		continue
	fi

	cd ${i}
	makepkg
	sudo pacman -U *.tar.xz
	cd ..
done
